import blockContent from './blockContent'
import indexroom from './indexroom'
import indexroomdescription from './indexroomdescription'
import roomdescription from './roomdescription'
import eventdescription from './eventdescription'
import room from './room'
import attrazione from './attrazione'
import attrazionedescription from './attrazionedescription'
import slider from './slider'
import service from './services'
import pricing from './pricing'
import indexabout from './indexabout'
import footer from './footer'
import events from './events'
import gallery from './gallery'
import contacts from './contacts'

export const schemaTypes = [slider, indexabout, indexroomdescription, indexroom, gallery, roomdescription, room, attrazione, attrazionedescription, service, pricing, eventdescription, events, contacts, footer, blockContent]
